-- FAIT_GRH_DECISION_CARRIERE — Source : GRH_DECISION_CARRIERE (full reload)
SELECT
    DECI_NO,
    PERS_ID,
    CAR_ID,
    UA_CODE,
    STATUT,
    FNCT_CODE,
    PROF_CODE,
    DATE_INSERT,
    USER_INSERT,
    DATE_UPDATE,
    USER_UPDATE
FROM USER_GRH.GRH_DECISION_CARRIERE
