-- FAIT_GRH_FACTURE — Source : GRH_FACTURE (full reload)
SELECT
    FAC_NO,
    CMED_CODE,
    DATE_ETABLIE,
    DATE_RECUE,
    MONTANT,
    REMARQUE,
    CODE_FACT,
    USER_INSERT,
    USER_UPDATE,
    DATE_UPDATE,
    DATE_INSERT,
    ETAT,
    DATE_ETAT,
    TYPE_FACT,
    DATE_TRAITEMENT,
    USER_LOCAL,
    LIB_CENTRE,
    DR_NO
FROM GRH_FACTURE
