-- FAIT_GRH_DEMANDE — Source : GRH_DEMANDE (full reload)
SELECT
    PERS_ID,
    SITU_ID,
    DMDE_NO,
    DATE_DMDE,
    CATEGORIE,
    DATE_RECEPTION,
    DATE_DEBUT,
    DATE_FIN,
    ABS_PERS_ID,
    ABS_SITU_ID,
    STATUT,
    OBSERVATION,
    ABSE_NO,
    USER_UPDATE,
    DATE_UPDATE,
    USER_INSERT,
    DATE_INSERT,
    DMDE_VERIFIE,
    USER_CAISSE,
    PER_CODE
FROM GRH_DEMANDE
