-- FAIT_GRH_MOUVEMENT — Source : GRH_MOUVEMENT (full reload)
SELECT
    MVT_ID,
    NATURE_MVT,
    DATE_DEBUT,
    DATE_SAISIE,
    REFERENCE,
    SITU_ID,
    UA_CODE,
    PERS_ID,
    DATE_FIN,
    FNCT_CODE,
    USER_INSERT,
    USER_UPDATE,
    DATE_INSERT,
    DATE_UPDATE,
    VALIDE,
    EXTERIEUR,
    CATEGORIE,
    ECHELLE,
    ECHELON
FROM GRH_MOUVEMENT
