-- FAIT_GRH_DECISION_PERSONNE — Source : GRH_DECISION_PERSONNE (full reload)
SELECT
    DECI_NO,
    PERS_ID,
    REF_CODE,
    UA_CODE,
    DEPART,
    RETOUR,
    STATUT,
    DEB_PERIODE,
    F_PERIODE,
    JOUR_DEDUCT,
    CONGE_SUPP_FNCT,
    CONGE_SUPP_ANC,
    REGUL,
    USER_INSERT,
    USER_UPDATE,
    DATE_INSERT,
    DATE_UPDATE,
    JOUR_TOT
FROM USER_GRH.GRH_DECISION_PERSONNE
