-- FAIT_GRH_SANCTION — Source : GRH_SANCTION (full reload)
SELECT
    PERS_ID,
    SANC_NO,
    DATE_SANCTION,
    MOTIF,
    CSAN_NO,
    DEGRE,
    OBSERVATION,
    ANNEE,
    USER_INSERT,
    DATE_INSERT,
    USER_UPDATE,
    DATE_UPDATE,
    RANG,
    UA_CODE,
    FNCT_CODE,
    CATEGORIE,
    ECHELLE,
    ECHELON,
    EN_TETE,
    SECT_CODE,
    STATUT
FROM USER_GRH.GRH_SANCTION
