SELECT
    CAI_USERNAME,
    CAI_NOM,
    CAI_PRENOM,
    CAI_ACTIF,
    CAI_RESP,
    CAI_DATE_INSERT,
    CAI_DATE_UPDATE,
    CAI_USAGER_INSERT,
    CAI_USAGER_UPDATE,
    CAI_USERNAME_RESP,
    LP_NO,
    DR_NO,
    SP_NO
FROM CAISSIER
