SELECT
    DR_NO,
    LP_NO,
    CAP_ID,
    CAP_DATE_FERMETURE,
    CAP_DATE_INSERT,
    CAP_USAGER_INSERT,
    CAP_DATE_UPDATE,
    CAP_USAGER_UPDATE,
    CAP_ACTIVE,
    SP_NO
FROM CAISSE_PAIEMENT
