SELECT
    CON_ID,
    CON_TYPE,
    CON_USERNAME,
    CON_NOM,
    CON_PRENOM,
    CON_DATE_FIN,
    CON_DATE_INSERT,
    CON_DATE_UPDATE,
    CON_USAGER_INSERT,
    CON_USAGER_UPDATE,
    DR_NO,
    SP_NO
FROM CONTROLEUR
