SELECT
    CODE_CAISSE,
    CODE_JOURNAL,
    CPT_COMPTABLE,
    LIBELLE_CAISSE,
    DR_NO,
    LP_NO,
    CRD_DATE_INSERT,
    CRD_USAGER_INSERT,
    CRD_DATE_UPDATE,
    CRD_USAGER_UPDATE,
    ANC_CAISSE,
    CRD_SENS,
    SP_NO,
    CAP_ACTIF
FROM PARAM_CAISSE_REC_DEP
