SELECT
    PR_NO,
    PR_DESC,
    PA_NO,
    PR_DATE_INSERT,
    PR_DATE_UPDATE,
    PR_USAGER_INSERT,
    PR_USAGER_UPDATE,
    PR_CHEF_LIEU,
    REG_CODE,
    PR_CHEF_LIEUX,
    PR_CODE_GL,
    PR_CODE_GRH,
    PR_ACTIVE
FROM PROVINCE
