-- Dimension REGION : combine DIRECTION_REGIONALE, SERVICE_PROVINCIAL, LIEU_PAIEMENT
SELECT
    dr.DR_NO,
    dr.DR_DESC AS LIBELLE_DR,
    sp.SP_NO,
    sp.SP_DESC AS LIBELLE_SP,
    lp.LP_NO,
    lp.LP_DESC AS LIBELLE_LP
FROM DIRECTION_REGIONALE dr
LEFT JOIN SERVICE_PROVINCIAL sp ON dr.DR_NO = sp.DR_NO
LEFT JOIN LIEU_PAIEMENT lp ON sp.SP_NO = lp.SP_NO
WHERE dr.DR_ACTIF = 'Y' 
   OR sp.SP_ACTIVE = 'Y'
   OR lp.LP_NO IS NOT NULL
ORDER BY dr.DR_NO, sp.SP_NO, lp.LP_NO
