SELECT
    EMP_REGIME,
    LIB_REGIME,
    CPT_DEBITEUR,
    CPT_CREDITEUR,
    COD_JOU,
    COD_GESTION,
    CPT_ATTESTATION,
    COD_GESTION_ATT,
    REG_ABREVIATION,
    CPT_ATTENTE
FROM REGIME_EMPLOYEUR
