SELECT
    TDOS_CODE,
    TDOS_DESCRIPTION,
    TDOS_MULT_ACTIF_ASSURE,
    TDOS_MULT_ASSURE,
    TDOS_DATE_INSERT,
    TDOS_USAGER_INSERT,
    TDOS_DATE_UPDATE,
    TDOS_USAGER_UPDATE,
    CODE_JOURNAL,
    CODE_GESTION,
    CODE_SECTION,
    BR_CODE
FROM TYPE_DOSSIER
