SELECT
    TPJ_CODE,
    TPJ_DESCRIPTION,
    TPJ_DUREE_VIE,
    TPJ_DATE_INSERT,
    TPJ_USAGER_INSERT,
    TPJ_DATE_UPDATE,
    TPJ_USAGER_UPDATE,
    TPJ_ACTIF,
    TPJ_LIBELLE_DATE_VALIDITE
FROM TYPE_PIECE
