-- select count(*) from DIM_SINISTRE
-- where rownum < 10
-- SELECT a.table_name,
--        a.constraint_name,
--        a.r_constraint_name
-- FROM user_constraints a
-- WHERE a.constraint_type = 'R'
-- AND a.r_constraint_name IN (

--     SELECT constraint_name
--     FROM user_constraints
--     WHERE table_name = 'DIM_SINISTRE'
-- );

-- select COUNT(*) from fait_transaction_cotisation
-- WHERE rownum < 10
-- TRUNCATE TABLE FAIT_TSINISTRE
-- ALTER TABLE FAIT_TSINISTRE  ADD (L_ANNEE NUMBER(4), L_MOIS
--   NUMBER(2));
-- TRUNCATE TABLE FAIT_CATEGORIE_EMPLOYEUR;


-- TRUNCATE TABLE FAIT_CONTRAINTE;
-- TRUNCATE TABLE FAIT_CONTROLE;
-- TRUNCATE TABLE FAIT_DECLARATION_NOMINATIVE;
-- TRUNCATE TABLE FAIT_DEPOT;
-- TRUNCATE TABLE FAIT_DOSSIER_IMMATRICULATION;
-- TRUNCATE TABLE FAIT_EMPLOI;
-- TRUNCATE TABLE FAIT_EMPLOYEUR;
-- TRUNCATE TABLE FAIT_INDIVIDU;
-- TRUNCATE TABLE FAIT_MISE_EN_DEMEURE;
-- TRUNCATE TABLE FAIT_NOTIFICATION_PREST;
-- TRUNCATE TABLE FAIT_PARTENAIRE_ASSURANCE;
-- TRUNCATE TABLE FAIT_PENALITE_RETARD;
-- TRUNCATE TABLE FAIT_PRESTATION_ESP;
-- TRUNCATE TABLE FAIT_RECEPTION_DOSSIER;
-- TRUNCATE TABLE FAIT_TRANSACTION_COTISATION;
-- TRUNCATE TABLE FAIT_TRANSACTION_DECLARATION;
-- TRUNCATE TABLE FAIT_TRANSACTION_REGLEMENT;
-- TRUNCATE TABLE FAIT_TRAVAILLEUR;
-- TRUNCATE TABLE FAIT_TSINISTRE;

-- ALTER TABLE FAIT_CATEGORIE_EMPLOYEUR DROP COLUMN L_MOIS;
-- ALTER TABLE FAIT_CATEGORIE_EMPLOYEUR DROP COLUMN L_ANNEE;
-- ALTER TABLE FAIT_CATEGORIE_EMPLOYEUR ADD CLICHE CHAR(6);

-- ALTER TABLE FAIT_CONTRAINTE DROP COLUMN L_MOIS;
-- ALTER TABLE FAIT_CONTRAINTE DROP COLUMN L_ANNEE;
-- ALTER TABLE FAIT_CONTRAINTE ADD CLICHE CHAR(6);

-- ALTER TABLE FAIT_CONTROLE DROP COLUMN L_MOIS;
-- ALTER TABLE FAIT_CONTROLE DROP COLUMN L_ANNEE;
-- ALTER TABLE FAIT_CONTROLE ADD CLICHE CHAR(6);

-- ALTER TABLE FAIT_DECLARATION_NOMINATIVE DROP COLUMN L_MOIS;
-- ALTER TABLE FAIT_DECLARATION_NOMINATIVE DROP COLUMN L_ANNEE;
-- ALTER TABLE FAIT_DECLARATION_NOMINATIVE ADD CLICHE CHAR(6);

-- ALTER TABLE FAIT_DEPOT DROP COLUMN L_MOIS;
-- ALTER TABLE FAIT_DEPOT DROP COLUMN L_ANNEE;
-- ALTER TABLE FAIT_DEPOT ADD CLICHE CHAR(6);

-- ALTER TABLE FAIT_DOSSIER_IMMATRICULATION DROP COLUMN L_MOIS;
-- ALTER TABLE FAIT_DOSSIER_IMMATRICULATION DROP COLUMN L_ANNEE;
-- ALTER TABLE FAIT_DOSSIER_IMMATRICULATION ADD CLICHE CHAR(6);

-- ALTER TABLE FAIT_EMPLOI DROP COLUMN L_MOIS;
-- ALTER TABLE FAIT_EMPLOI DROP COLUMN L_ANNEE;
-- ALTER TABLE FAIT_EMPLOI ADD CLICHE CHAR(6);

-- ALTER TABLE FAIT_EMPLOYEUR DROP COLUMN L_MOIS;
-- ALTER TABLE FAIT_EMPLOYEUR DROP COLUMN L_ANNEE;
-- ALTER TABLE FAIT_EMPLOYEUR ADD CLICHE CHAR(6);

-- ALTER TABLE FAIT_INDIVIDU DROP COLUMN L_MOIS;
-- ALTER TABLE FAIT_INDIVIDU DROP COLUMN L_ANNEE;
-- ALTER TABLE FAIT_INDIVIDU ADD CLICHE CHAR(6);

-- ALTER TABLE FAIT_MISE_EN_DEMEURE DROP COLUMN L_MOIS;
-- ALTER TABLE FAIT_MISE_EN_DEMEURE DROP COLUMN L_ANNEE;
-- ALTER TABLE FAIT_MISE_EN_DEMEURE ADD CLICHE CHAR(6);

-- ALTER TABLE FAIT_NOTIFICATION_PREST DROP COLUMN L_MOIS;
-- ALTER TABLE FAIT_NOTIFICATION_PREST DROP COLUMN L_ANNEE;
-- ALTER TABLE FAIT_NOTIFICATION_PREST ADD CLICHE CHAR(6);

-- ALTER TABLE FAIT_PARTENAIRE_ASSURANCE DROP COLUMN L_MOIS;
-- ALTER TABLE FAIT_PARTENAIRE_ASSURANCE DROP COLUMN L_ANNEE;
-- ALTER TABLE FAIT_PARTENAIRE_ASSURANCE ADD CLICHE CHAR(6);

-- ALTER TABLE FAIT_PENALITE_RETARD DROP COLUMN L_MOIS;
-- ALTER TABLE FAIT_PENALITE_RETARD DROP COLUMN L_ANNEE;
-- ALTER TABLE FAIT_PENALITE_RETARD ADD CLICHE CHAR(6);

-- ALTER TABLE FAIT_PRESTATION_ESP DROP COLUMN L_MOIS;
-- ALTER TABLE FAIT_PRESTATION_ESP DROP COLUMN L_ANNEE;
-- ALTER TABLE FAIT_PRESTATION_ESP ADD CLICHE CHAR(6);

-- ALTER TABLE FAIT_RECEPTION_DOSSIER DROP COLUMN L_MOIS;
-- ALTER TABLE FAIT_RECEPTION_DOSSIER DROP COLUMN L_ANNEE;
-- ALTER TABLE FAIT_RECEPTION_DOSSIER ADD CLICHE CHAR(6);

-- ALTER TABLE FAIT_TRANSACTION_COTISATION DROP COLUMN L_MOIS;
-- ALTER TABLE FAIT_TRANSACTION_COTISATION DROP COLUMN L_ANNEE;
-- ALTER TABLE FAIT_TRANSACTION_COTISATION ADD CLICHE CHAR(6);

-- ALTER TABLE FAIT_TRANSACTION_DECLARATION DROP COLUMN L_MOIS;
-- ALTER TABLE FAIT_TRANSACTION_DECLARATION DROP COLUMN L_ANNEE;
-- ALTER TABLE FAIT_TRANSACTION_DECLARATION ADD CLICHE CHAR(6);

-- ALTER TABLE FAIT_TRANSACTION_REGLEMENT DROP COLUMN L_MOIS;
-- ALTER TABLE FAIT_TRANSACTION_REGLEMENT DROP COLUMN L_ANNEE;
-- ALTER TABLE FAIT_TRANSACTION_REGLEMENT ADD CLICHE CHAR(6);

-- ALTER TABLE FAIT_TRAVAILLEUR DROP COLUMN L_MOIS;
-- ALTER TABLE FAIT_TRAVAILLEUR DROP COLUMN L_ANNEE;
-- ALTER TABLE FAIT_TRAVAILLEUR ADD CLICHE CHAR(6);

-- ALTER TABLE FAIT_TSINISTRE DROP COLUMN L_MOIS;
-- ALTER TABLE FAIT_TSINISTRE DROP COLUMN L_ANNEE;
-- ALTER TABLE FAIT_TSINISTRE ADD CLICHE CHAR(6);

















-- CREATE INDEX IDX_CLICHE_CATEMP ON FAIT_CATEGORIE_EMPLOYEUR (CLICHE);
-- CREATE INDEX IDX_CLICHE_CONTR ON FAIT_CONTRAINTE (CLICHE);
-- CREATE INDEX IDX_CLICHE_CONT ON FAIT_CONTROLE (CLICHE);
-- CREATE INDEX IDX_CLICHE_DECLNOM ON FAIT_DECLARATION_NOMINATIVE (CLICHE);
-- CREATE INDEX IDX_CLICHE_DEPOT ON FAIT_DEPOT (CLICHE);
-- CREATE INDEX IDX_CLICHE_DOSIM ON FAIT_DOSSIER_IMMATRICULATION (CLICHE);
-- CREATE INDEX IDX_CLICHE_EMP ON FAIT_EMPLOI (CLICHE);
-- CREATE INDEX IDX_CLICHE_EMPLO ON FAIT_EMPLOYEUR (CLICHE);
-- CREATE INDEX IDX_CLICHE_IND ON FAIT_INDIVIDU (CLICHE);
-- CREATE INDEX IDX_CLICHE_DEMEUR ON FAIT_MISE_EN_DEMEURE (CLICHE);
-- CREATE INDEX IDX_CLICHE_NOTIF ON FAIT_NOTIFICATION_PREST (CLICHE);
-- CREATE INDEX IDX_CLICHE_PARTA ON FAIT_PARTENAIRE_ASSURANCE (CLICHE);
-- CREATE INDEX IDX_CLICHE_PENAL ON FAIT_PENALITE_RETARD (CLICHE);
-- CREATE INDEX IDX_CLICHE_PREST ON FAIT_PRESTATION_ESP (CLICHE);
-- CREATE INDEX IDX_CLICHE_RECDOS ON FAIT_RECEPTION_DOSSIER (CLICHE);
-- CREATE INDEX IDX_CLICHE_TRACOT ON FAIT_TRANSACTION_COTISATION (CLICHE);
-- CREATE INDEX IDX_CLICHE_TRADEC ON FAIT_TRANSACTION_DECLARATION (CLICHE);
-- CREATE INDEX IDX_CLICHE_TRAREG ON FAIT_TRANSACTION_REGLEMENT (CLICHE);
-- CREATE INDEX IDX_CLICHE_TRAV ON FAIT_TRAVAILLEUR (CLICHE);
-- CREATE INDEX IDX_CLICHE_TSIN ON FAIT_TSINISTRE (CLICHE);

-- TRUNCATE TABLE FAIT_TRANSACTION_COTISATION