
-- Donner les droits sur toutes les tables du schema DTM
BEGIN
    FOR t IN (
        SELECT table_name 
        FROM all_tables 
        WHERE owner = 'ODS'
    )
    LOOP
        EXECUTE IMMEDIATE 
        'GRANT SELECT, INSERT, UPDATE, DELETE ON ODS.' 
        || t.table_name || 
        ' TO DWH';
    END LOOP;
END;
-- /
-- BEGIN
--     FOR s IN (
--         SELECT sequence_name 
--         FROM all_sequences 
--         WHERE sequence_owner = 'ODS'
--     )
--     LOOP
--         EXECUTE IMMEDIATE 
--         'GRANT SELECT ON ODS.' 
--         || s.sequence_name || 
--         ' TO DWH';
--     END LOOP;
-- END;

-- Exemple pour une table
-- Création des index sur la colonne CLICHE pour toutes les tables FAIT_%

-- CREATE INDEX IDX_CLICHE_CATEMP ON FAIT_CATEGORIE_EMPLOYEUR (CLICHE);
-- CREATE INDEX IDX_CLICHE_CONTR ON FAIT_CONTRAINTE (CLICHE);
-- CREATE INDEX IDX_CLICHE_CONT ON FAIT_CONTROLE (CLICHE);
-- CREATE INDEX IDX_CLICHE_DECLNOM ON FAIT_DECLARATION_NOMINATIVE (CLICHE);
-- CREATE INDEX IDX_CLICHE_DEPOT ON FAIT_DEPOT (CLICHE);
-- CREATE INDEX IDX_CLICHE_DOSIM ON FAIT_DOSSIER_IMMATRICULATION (CLICHE);
-- CREATE INDEX IDX_CLICHE_EMP ON FAIT_EMPLOI (CLICHE);
-- CREATE INDEX IDX_CLICHE_EMPLO ON FAIT_EMPLOYEUR (CLICHE);
-- CREATE INDEX IDX_CLICHE_IND ON FAIT_INDIVIDU (CLICHE);
-- CREATE INDEX IDX_CLICHE_DEMEUR ON FAIT_MISE_EN_DEMEURE (CLICHE);
-- CREATE INDEX IDX_CLICHE_NOTIF ON FAIT_NOTIFICATION_PREST (CLICHE);
-- CREATE INDEX IDX_CLICHE_PARTA ON FAIT_PARTENAIRE_ASSURANCE (CLICHE);
-- CREATE INDEX IDX_CLICHE_PENAL ON FAIT_PENALITE_RETARD (CLICHE);
-- CREATE INDEX IDX_CLICHE_PREST ON FAIT_PRESTATION_ESP (CLICHE);
-- CREATE INDEX IDX_CLICHE_RECDOS ON FAIT_RECEPTION_DOSSIER (CLICHE);
-- CREATE INDEX IDX_CLICHE_TRACOT ON FAIT_TRANSACTION_COTISATION (CLICHE);
-- CREATE INDEX IDX_CLICHE_TRADEC ON FAIT_TRANSACTION_DECLARATION (CLICHE);
-- CREATE INDEX IDX_CLICHE_TRAREG ON FAIT_TRANSACTION_REGLEMENT (CLICHE);
-- CREATE INDEX IDX_CLICHE_TRAV ON FAIT_TRAVAILLEUR (CLICHE);
-- CREATE INDEX IDX_CLICHE_TSIN ON FAIT_TSINISTRE (CLICHE);
-- GRANT SELECT, INSERT, DELETE ON ods.FAIT_APPEL TO dwh;
-- GRANT SELECT, INSERT, DELETE ON ods.FAIT_BORDEREAU_PREST TO dwh;
-- GRANT SELECT, INSERT, DELETE ON ods.FAIT_DEBOURS TO dwh;
-- GRANT SELECT, INSERT, DELETE ON ods.FAIT_DECLARAT_GROUPE_ASSURANCE TO dwh;
-- GRANT SELECT, INSERT, DELETE ON ods.FAIT_DOSSIER TO dwh;
-- GRANT SELECT, INSERT, DELETE ON ods.FAIT_ECHEANCIER TO dwh;
-- GRANT SELECT, INSERT, DELETE ON ods.FAIT_EFFET TO dwh;
-- GRANT SELECT, INSERT, DELETE ON ods.FAIT_ELEMENT_CONTROLE TO dwh;
-- GRANT SELECT, INSERT, DELETE ON ods.FAIT_ELEMENT_TAXATION TO dwh;
-- GRANT SELECT, INSERT, DELETE ON ods.FAIT_ETAPE TO dwh;
-- GRANT SELECT, INSERT, DELETE ON ods.FAIT_IND_COMPTE_BANCAIRE TO dwh;
-- GRANT SELECT, INSERT, DELETE ON ods.FAIT_INSTITUTION_FINANCIERE TO dwh;
-- GRANT SELECT, INSERT, DELETE ON ods.FAIT_LIEN TO dwh;
-- GRANT SELECT, INSERT, DELETE ON ods.FAIT_PERIODE_COTISATION TO dwh;
-- GRANT SELECT, INSERT, DELETE ON ods.FAIT_PE_AJ TO dwh;
-- GRANT SELECT, INSERT, DELETE ON ods.FAIT_RECEPTION_DOS_PIECE TO dwh;
-- GRANT SELECT, INSERT, DELETE ON ods.FAIT_REDEVANCE TO dwh;
-- GRANT SELECT, INSERT, DELETE ON ods.FAIT_SALAIRE TO dwh;
-- GRANT SELECT, INSERT, DELETE ON ods.FAIT_SUPPLEMENT_SALAIRE TO dwh;
-- GRANT SELECT, INSERT, DELETE ON ods.FAIT_TAXATION_DOFFICE TO dwh;
-- GRANT SELECT, INSERT, DELETE ON ods.FAIT_IXDEPOT TO dwh;
-- GRANT SELECT, INSERT, DELETE ON ods.FAIT_CATEGORIE_EMPLOYEUR TO dwh;    
-- GRANT SELECT, INSERT, DELETE ON ods.FAIT_CONTRAINTE TO dwh;
-- GRANT SELECT, INSERT, DELETE ON ods.FAIT_CONTROLE TO dwh;
-- GRANT SELECT, INSERT, DELETE ON ods.FAIT_DECLARATION_NOMINATIVE TO dwh; 
-- GRANT SELECT, INSERT, DELETE ON ods.FAIT_DEPOT TO dwh;
-- GRANT SELECT, INSERT, DELETE ON ods.FAIT_DOSSIER_IMMATRICULATION TO dwh;
-- GRANT SELECT, INSERT, DELETE ON ods.FAIT_EMPLOI TO dwh;
-- GRANT SELECT, INSERT, DELETE ON ods.FAIT_EMPLOYEUR TO dwh;
-- GRANT SELECT, INSERT, DELETE ON ods.FAIT_INDIVIDU TO dwh;
-- GRANT SELECT, INSERT, DELETE ON ods.FAIT_MISE_EN_DEMEURE TO dwh;        
-- GRANT SELECT, INSERT, DELETE ON ods.FAIT_NOTIFICATION_PREST TO dwh;     
-- GRANT SELECT, INSERT, DELETE ON ods.FAIT_PARTENAIRE_ASSURANCE TO dwh;   
-- GRANT SELECT, INSERT, DELETE ON ods.FAIT_PENALITE_RETARD TO dwh;        
-- GRANT SELECT, INSERT, DELETE ON ods.FAIT_PRESTATION_ESP TO dwh;
-- GRANT SELECT, INSERT, DELETE ON ods.FAIT_RECEPTION_DOSSIER TO dwh;      
-- GRANT SELECT, INSERT, DELETE ON ods.FAIT_TRANSACTION_COTISATION TO dwh; 
-- GRANT SELECT, INSERT, DELETE ON ods.FAIT_TRANSACTION_DECLARATION TO dwh;
-- GRANT SELECT, INSERT, DELETE ON ods.FAIT_TRANSACTION_REGLEMENT TO dwh;  
-- GRANT SELECT, INSERT, DELETE ON ods.FAIT_TRAVAILLEUR TO dwh;
-- GRANT SELECT, INSERT, DELETE ON ods.FAIT_TSINISTRE TO dwh;
