-- DIM_GRH_CAT_ABSENCE — Source : GRH_CAT_ABSENCE (full reload)
SELECT
    CABS_CODE,
    DESCRIPTION,
    CABS_TYPE,
    DUREE,
    UNITE,
    CABS_CODE_SUP,
    GEN_DEC,
    CATEGORIE,
    CDEC_CODE
FROM USER_GRH.GRH_CAT_ABSENCE
