-- DIM_GRH_FORMATION — Source : GRH_FORMATION (full reload)
SELECT
    FORM_NO,
    UA_CODE,
    DESIGNATION,
    CATEGORIE,
    LIEU_STAGE,
    DATE_DEBUT,
    DATE_FIN,
    STATUT,
    COUT_TOTAL,
    DATE_DEPART,
    DATE_RETOUR,
    USER_INSERT,
    USER_UPDATE,
    DATE_INSERT,
    DATE_UPDATE,
    BUDGET,
    COUT_HONORAIRE,
    NBRE_INSCRIT,
    REF_FORMA,
    SIM_FORMA_AUTO
FROM GRH_FORMATION
