-- DIM_GRH_CENTRE_MEDICAL — Source : GRH_CENTRE_MEDICAL (full reload)
SELECT
    CMED_CODE,
    DESCRIPTION,
    ADRESSE,
    CATEGORIE,
    PAYS_ID,
    CMED_TYPE,
    DR_NO,
    CODE_REGION,
    ETAT
FROM USER_GRH.GRH_CENTRE_MEDICAL
