-- DTM_DECLARATION — Étape 2/3 : UPDATE NB_EMP_EMIS + NB_TR_EMIS
-- Source : DWH.FAIT_TRANSACTION_DECLARATION (TXDE_TYPE='D', EMP_PERIODICITE='T')
-- Fenêtre : années N-1 et N-2 relative à SYSDATE
-- ID_TEMPS_SUIVANT = premier mois du trimestre suivant (décalage déclaratif trimestriel)
-- NB_EMP_EMIS : COUNT(DISTINCT EMP_ID) trimestre T-1
-- NB_TR_EMIS  : SUM(TXDE_NB_TOTAL)     trimestre T-1
-- :1 = CLICHE (MMYYYY) — utilisé uniquement dans le CREATE TABLE AS SELECT

CREATE TABLE DTM.TMP_EMIS AS
SELECT
    CASE
        WHEN CEIL(EXTRACT(MONTH FROM TO_DATE(TO_CHAR(td.PER_ID_AU),'YYYYMM'))/3) = 1
             THEN TO_NUMBER(TO_CHAR(EXTRACT(YEAR FROM TO_DATE(TO_CHAR(td.PER_ID_AU),'YYYYMM')))||'0401')
        WHEN CEIL(EXTRACT(MONTH FROM TO_DATE(TO_CHAR(td.PER_ID_AU),'YYYYMM'))/3) = 2
             THEN TO_NUMBER(TO_CHAR(EXTRACT(YEAR FROM TO_DATE(TO_CHAR(td.PER_ID_AU),'YYYYMM')))||'0701')
        WHEN CEIL(EXTRACT(MONTH FROM TO_DATE(TO_CHAR(td.PER_ID_AU),'YYYYMM'))/3) = 3
             THEN TO_NUMBER(TO_CHAR(EXTRACT(YEAR FROM TO_DATE(TO_CHAR(td.PER_ID_AU),'YYYYMM')))||'1001')
        WHEN CEIL(EXTRACT(MONTH FROM TO_DATE(TO_CHAR(td.PER_ID_AU),'YYYYMM'))/3) = 4
             THEN TO_NUMBER(TO_CHAR(EXTRACT(YEAR FROM TO_DATE(TO_CHAR(td.PER_ID_AU),'YYYYMM'))+1)||'0101')
    END                                                          AS ID_TEMPS_SUIVANT,
    NVL(
        CASE WHEN td.DR_NO IS NOT NULL THEN td.DR_NO
             WHEN sp.DR_NO IS NOT NULL THEN sp.DR_NO
        END,
        99
    )                                                            AS DR_NO,
    e.EMP_REGIME,
    NVL(e.SA_NO, 99)                                             AS SA_NO,
    NVL(fj.FJ_CODE, 'X')                                        AS FJ_CODE,
    dp.ID_PERIODICITE,
    tef.TEF_CODE,
    COUNT(DISTINCT td.EMP_ID)                                    AS NB_EMP_PREV,
    SUM(td.TXDE_NB_TOTAL)                                        AS NB_TR_PREV
FROM DWH.FAIT_TRANSACTION_DECLARATION                            td
LEFT JOIN DWH.FAIT_EMPLOYEUR            e   ON e.EMP_ID          = td.EMP_ID
LEFT JOIN DTM.DIM_SERVICE_PROVINCIAL    sp  ON sp.SP_NO          = e.SP_NO
LEFT JOIN DTM.DIM_FORME_JURIDIQUE       fj  ON fj.FJ_CODE        = e.EMP_FORME_JURIDIQUE
LEFT JOIN DTM.DIM_PERIODICITE_VERSEMENT dp  ON dp.CODE_PERIODICITE = e.EMP_PERIODICITE
LEFT JOIN DTM.DIM_TRANCHE_EFFECTIF      tef ON e.EMP_NO_TR_DECLAR BETWEEN tef.INF AND tef.SUP
WHERE td.CLICHE          = :1
  AND td.TXDE_TYPE       = 'D'
  AND td.EMP_PERIODICITE = 'T'
  AND EXTRACT(YEAR FROM TO_DATE(TO_CHAR(td.PER_ID_AU),'YYYYMM'))
      IN (EXTRACT(YEAR FROM SYSDATE)-1, EXTRACT(YEAR FROM SYSDATE)-2)
GROUP BY
    CASE
        WHEN CEIL(EXTRACT(MONTH FROM TO_DATE(TO_CHAR(td.PER_ID_AU),'YYYYMM'))/3) = 1
             THEN TO_NUMBER(TO_CHAR(EXTRACT(YEAR FROM TO_DATE(TO_CHAR(td.PER_ID_AU),'YYYYMM')))||'0401')
        WHEN CEIL(EXTRACT(MONTH FROM TO_DATE(TO_CHAR(td.PER_ID_AU),'YYYYMM'))/3) = 2
             THEN TO_NUMBER(TO_CHAR(EXTRACT(YEAR FROM TO_DATE(TO_CHAR(td.PER_ID_AU),'YYYYMM')))||'0701')
        WHEN CEIL(EXTRACT(MONTH FROM TO_DATE(TO_CHAR(td.PER_ID_AU),'YYYYMM'))/3) = 3
             THEN TO_NUMBER(TO_CHAR(EXTRACT(YEAR FROM TO_DATE(TO_CHAR(td.PER_ID_AU),'YYYYMM')))||'1001')
        WHEN CEIL(EXTRACT(MONTH FROM TO_DATE(TO_CHAR(td.PER_ID_AU),'YYYYMM'))/3) = 4
             THEN TO_NUMBER(TO_CHAR(EXTRACT(YEAR FROM TO_DATE(TO_CHAR(td.PER_ID_AU),'YYYYMM'))+1)||'0101')
    END,
    NVL(CASE WHEN td.DR_NO IS NOT NULL THEN td.DR_NO
             WHEN sp.DR_NO IS NOT NULL THEN sp.DR_NO END, 99),
    e.EMP_REGIME, NVL(e.SA_NO, 99), NVL(fj.FJ_CODE,'X'),
    dp.ID_PERIODICITE, tef.TEF_CODE;

CREATE INDEX DTM.IDX_TMP_EMIS ON DTM.TMP_EMIS
    (ID_TEMPS_SUIVANT, DR_NO, EMP_REGIME, SA_NO, FJ_CODE, ID_PERIODICITE, TEF_CODE);

UPDATE DTM.DTM_DECLARATION d
SET (d.NB_EMP_EMIS, d.NB_TR_EMIS) = (
    SELECT t.NB_EMP_PREV, t.NB_TR_PREV
    FROM DTM.TMP_EMIS t
    WHERE  t.ID_TEMPS_SUIVANT = d.ID_TEMPS
      AND (t.DR_NO            = d.DR_NO          OR (t.DR_NO IS NULL          AND d.DR_NO IS NULL))
      AND (t.EMP_REGIME       = d.EMP_REGIME     OR (t.EMP_REGIME IS NULL     AND d.EMP_REGIME IS NULL))
      AND (t.SA_NO            = d.SA_NO          OR (t.SA_NO IS NULL          AND d.SA_NO IS NULL))
      AND  t.FJ_CODE          = d.FJ_CODE
      AND (t.ID_PERIODICITE   = d.ID_PERIODICITE OR (t.ID_PERIODICITE IS NULL AND d.ID_PERIODICITE IS NULL))
      AND (t.TEF_CODE         = d.TEF_CODE       OR (t.TEF_CODE IS NULL       AND d.TEF_CODE IS NULL))
);

DROP TABLE DTM.TMP_EMIS PURGE
