-- FAIT_CATEGORIE_EMPLOYEUR — Source : CATEGORIE_EMPLOYEUR
SELECT
    CAT_CODE,
    SCAT_CODE,
    ACT_CODE,
    EMP_ID,
    CAT_USAGER_INSERT,
    CAT_DATE_INSERT,
    CAT_USAGER_UPDATE,
    CAT_DATE_UPDATE
FROM CATEGORIE_EMPLOYEUR
