-- FAIT_DOSSIERS_CONTROLES — Source : USER_DWH.DOSSIERS_CONTROLES
SELECT
    DC_ID,
    TDOS_CODE,
    DOS_CODE,
    TPE_CODE,
    DC_DATE_CONTROLE,
    AUD_ID,
    MCI_ID,
    DC_REMARQUE,
    DC_DATE_INSERT,
    DC_USAGER_INSERT,
    DC_DATE_UPDATE,
    DC_USAGER_UPDATE,
    DC_RECOMMANDE
FROM DOSSIERS_CONTROLES
