-- FAIT_CONTRAINTE — Source : CONTRAINTE
SELECT
    CTR_ID,
    EMP_ID,
    DR_NO,
    MED_DR_NO,
    MED_ID,
    CTR_DATE,
    CTR_PER_DU,
    CTR_PER_AU,
    CTR_MNT_CP,
    CTR_MNT_RT,
    CTR_MNT_NP,
    CTR_NOTE,
    CTR_ACCEPTER,
    CTR_ANNULER,
    CTR_DATE_INSERT,
    CTR_USAGER_INSERT,
    CTR_DATE_UPDATE,
    CTR_USAGER_UPDATE,
    CTR_REGUL,
    SIGN_ID
FROM CONTRAINTE
