-- FAIT_DECLARAT_GROUPE_ASSURANCE � Source : DECLARAT_GROUPE_ASSURANCE (full reload)
SELECT
    DGP_ID,
    DGP_DATE,
    DGP_BASE_MENSUELLE,
    DGP_PER_DEBUT,
    DGP_PER_FIN,
    DGP_STATUT,
    GAV_ID,
    LT_ID,
    DGP_ORIGINE,
    PAV_ID
FROM DECLARATION_GROUPE_ASSURANCE
