-- FAIT_DEPOT — Source : DEPOT
SELECT
    DEP_ID,
    DEP_TYPE,
    AG_CODE,
    IF_NO,
    COM_NO,
    DEP_MONTANT,
    DEP_DATE_DEPOSE,
    DEP_DATE_INSERT,
    DEP_USAGER_INSERT,
    DEP_DATE_UPDATE,
    DEP_USAGER_UPDATE,
    DEP_STATUT,
    DR_NO,
    SP_NO,
    DR_NO_CPT,
    DEP_DATE_DU,
    DEP_DATE_AU,
    DEP_REGUL
FROM DEPOT
