-- FAIT_DOSSIER_REJETE — Source : DOSSIER_REJETE (full reload)
SELECT
    DOSRE_ID,
    TDOS_CODE,
    DR_NO,
    LP_NO,
    RD_ID,
    TR_ID,
    DOSRE_DATE_REJET,
    DOSRE_MOTIF,
    DOSRE_REMARQUE,
    DOS_CODE,
    DOSRE_USAGER_INSERT,
    DOSRE_DATE_INSERT,
    DOSRE_USAGER_UPDATE,
    DOSRE_DATE_UPDATE
FROM DOSSIER_REJETE
