-- FAIT_DOSSIER_IMMATRICULATION — Source : DOSSIER_IMMATRICULATION
SELECT
    DI_ID,
    DI_DATE_RECEPTION,
    DI_TYPE,
    ANE_ANCIEN_CODE,
    EMP_ID,
    TR_NOM_PRENOM,
    ETAT,
    DR_NO,
    DI_USAGER_INSERT,
    DI_DATE_INSERT,
    DI_USAGER_UPDATE,
    DI_DATE_UPDATE
FROM DOSSIER_IMMATRICULATION
