-- FAIT_ELEMENT_TAXATION � Source : ELEMENT_TAXATION (full reload)
SELECT
    DR_NO,
    PER_ID,
    ETX_TYPE,
    PERIODICITE,
    TXO_ID,
    ETX_MNT_TAXATION,
    ETX_MNT_AV,
    ETX_MNT_AT,
    ETX_MNT_PF,
    ETX_NB_PERM,
    ETX_NB_TEMP,
    ETX_NB_JOUR,
    TXDE_ID
FROM ELEMENT_TAXATION
