-- FAIT_EMPLOI — Source : EMPLOI
SELECT
    TR_ID,
    EM_DATE_DEBUT,
    EMP_ID,
    EM_QUALIFICATION,
    EM_TYPE_EMPLOI,
    EM_DATE_FIN,
    EM_PROFESSION,
    EM_CATEGORIE,
    EM_ASSURE_VOL,
    EM_DATE_INSERT,
    EM_DATE_UPDATE,
    EM_USAGER_INSERT,
    EM_USAGER_UPDATE,
    EM_SALAIRE,
    EM_MOTIF_SORTIE,
    EM_REGUL,
    EM_ID,
    DMD_ID_ECNSS_INS,
    DMD_ID_ECNSS_UPD,
    SP_NO,
    SP_NO_UPD
FROM EMPLOI
