-- FAIT_ETAPE � Source : ETAPE (full reload)
SELECT
    EA_ID,
    PE_ID,
    TEA_CODE,
    EA_DATE_EFFET,
    EA_MONTANT,
    EA_REMARQUE,
    EA_SYSTEME,
    EA_VERIFIE,
    EA_DATE_INSERT,
    EA_USAGER_INSERT,
    EA_DATE_UPDATE,
    EA_USAGER_UPDATE,
    EA_ACTIVE,
    EA_REMARQUE2,
    EA_DATE_EXPIRE
FROM ETAPE
