-- FAIT_IND_COMPTE_BANCAIRE � Source : IND_COMPTE_BANCAIRE (full reload)
SELECT
    IND_ID,
    IF_NO,
    AG_CODE,
    COM_NO,
    INDCOM_DATE_INSERT,
    INDCOM_DATE_UPDATE,
    INDCOM_USAGER_INSERT,
    INDCOM_USAGER_UPDATE
FROM IND_COMPTE_BANCAIRE
