-- FAIT_INDIVIDU — Source : INDIVIDU
SELECT
    IND_ID,
    IND_NOM,
    IND_PRENOM,
    TR_ID,
    IND_DATE_NAISSANCE,
    IND_SEXE,
    IND_SITUATION_MATRI,
    IND_DATE_DECES,
    PA_NO,
    IND_TYPE_ENFANT,
    IND_PIECE_IDENTIFICATION,
    IND_VERIFIE,
    IND_ACTIF,
    IND_NOM_EPOUX,
    IND_ID_ECNSS,
    IND_DATE_INSERT,
    IND_DATE_UPDATE
FROM INDIVIDU
