-- FAIT_INSTITUTION_FINANCIERE � Source : INSTITUTION_FINANCIERE (full reload)
SELECT
    IF_NO,
    IF_DESC,
    IF_ADRESSE,
    IF_DATE_INSERT,
    IF_USAGER_INSERT,
    IF_DATE_UPDATE,
    IF_USAGER_UPDATE,
    IF_SIGLE,
    IF_TYPE,
    IF_ACTIVE,
    EMP_ID,
    IF_BVB_MIXTE,
    CODE_BANQUE
FROM INSTITUTION_FINANCIERE
