-- FAIT_PERIODE_COTISATION � Source : PERIODE_COTISATION (full reload)
SELECT
    PECO_ID,
    PER_ID,
    EMP_ID,
    TR_ID,
    ECH_ID,
    PECO_MAJORATION_TRAITE,
    PER_ID_MAJORATION,
    PECO_NB_TRAV,
    PECO_TXDE_TYPE,
    PECO_DATE_INSERT,
    PECO_USAGER_INSERT,
    PECO_DATE_UPDATE,
    PECO_USAGER_UPDATE,
    TYPE_PERIODICITE
FROM PERIODE_COTISATION
