-- FAIT_RECEPTION_DOS_PIECE � Source : RECEPTION_DOS_PIECE (full reload)
SELECT
    RD_ID,
    TPJ_CODE,
    RDP_QUANTITE,
    RDP_DATE_INSERT,
    RDP_USAGER_INSERT,
    RDP_DATE_UPDATE,
    RDP_USAGER_UPDATE
FROM RECEPTION_DOS_PIECE
