-- FAIT_REDEVANCE � Source : REDEVANCE (full reload)
SELECT
    RED_ID,
    PE_ID,
    ACA_CODE,
    RED_MONTANT,
    RED_REMARQUE,
    RED_VERIFIE,
    RED_DATE_INSERT,
    RED_USAGER_INSERT,
    RED_DATE_UPDATE,
    RED_USAGER_UPDATE,
    RED_DATE_EFFET,
    MAJ_CGRAE_2014,
    MT_MAJ_CGRAE_2014,
    ANCIEN_MT_CNPS_2018,
    RED_DATE_EXPIRATION,
    ANCIEN_MT_CARFO_2020,
    RED_ACTIF
FROM REDEVANCE
