-- FAIT_SUPPLEMENT_SALAIRE � Source : SUPPLEMENT_SALAIRE (full reload)
SELECT
    SUP_ID,
    SUP_TYPE,
    SUP_DATE_DEBUT,
    SUP_DATE_FIN,
    SUP_MONTANT,
    SUP_RELIQUAT,
    SAL_ID,
    BT_ID,
    DN_ID,
    SUP_STATUT,
    SUP_LIBELLE,
    SUP_SOUS_TYPE,
    SUP_USER_INSERT,
    SUP_DATE_INSERT,
    SUP_USER_UPDATE,
    SUP_DATE_UPDATE,
    SUP_ID_2
FROM SUPPLEMENT_SALAIRE
