-- FAIT_TRANSACTION_COTISATION — Source : TRANSACTION_COTISATION
SELECT
    PECO_ID,
    TXCO_TYPE,
    TXCO_SOUS_TYPE,
    TXDE_ID,
    TXRE_ID,
    TXCO_DATE,
    TXCO_MONTANT,
    TXCO_REVISE,
    TXDE_ID_REVISE_PAR,
    TXRE_ID_REVISE_PAR,
    TXCO_DATE_INSERT,
    TXCO_USAGER_INSERT,
    TXCO_DATE_UPDATE,
    TXCO_USAGER_UPDATE,
    TXCO_MONTANT_COMPTA,
    TXCO_DATE_COMPTA,
    DR_NO_CPT,
    TXCO_ID,
    TXM_ID,
    TXDE_ID_PERE
FROM TRANSACTION_COTISATION
