-- FAIT_TXDEPOT — Source : TXDEPOT
SELECT
    DEP_ID,
    TXRE_ID,
    TXD_DATE_INSERT,
    TXD_USAGER_INSERT,
    TXD_DATE_UPDATE,
    TXD_USAGER_UPDATE,
    TXD_STATUT,
    TXD_DATE_REMISE,
    TXD_DATE_ENCAISSEMENT,
    NUM_CPT_BANCAIRE
FROM TXDEPOT